# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt-get update
    sudo apt-get install unzip
    echo .....................
    echo Instalando terraform
    echo .....................
    wget https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_amd64.zip
    sudo apt install zip -y
    sudo unzip terraform_0.14.3_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    sudo apt-get install awscli
    sudo apt-get install python3-pip

  displayName: 'Instalaciones'
  - script:
    terraform version
    aws --version
    python3 -m awscli --version
  displayName: 'Ver versiones'