trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt-get update
    sudo apt-get install awscli
    sudo apt-get install python3-pip
    sudo apt-get install unzip
    wget https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip
    unzip terraform_0.12.7_linux_amd64.zip
    sudo mv terraform /usr/local/bin/

    echo -----*******************-------
    echo INSTALACIONES TERMINADAS
    echo -----*******************-------

  displayName: 'Instalaciones'
- script: |
    echo -----*******************-------
    echo VERIFICACION DE INSTALACIONES
    echo -----*******************-------
    python3 -m awscli --version
    aws --version
    terraform --version 
  displayName: 'Verificaciones'

- task: LambdaNETCoreDeploy@1
  inputs:
    awsCredentials: 'aws-user-admin'
    regionName: 'us-east-1'
    command: 'deployFunction'
    packageOnly: false
    functionName: 'start-ec2'
- task: LambdaNETCoreDeploy@1
  inputs:
    awsCredentials: 'aws-user-admin'
    regionName: 'us-east-1'
    command: 'deployFunction'
    packageOnly: false
    lambdaProjectPath: '$(System.DefaultWorkingDirectory)'
    functionName: 'start-ec2'

